version: "3.5"

services:
  mongodb:
    container_name: mongo_prd
    image: mongo:latest
    volumes:
      - ./mongo-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootDBUser
      - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd
      - MONGO_INITDB_DATABASE=wmsprodDB
    ports:
      - 27018:27017
    networks:
      - prd

  wmsapp:
    container_name: wmsapp
    image: shridha/wmsapp:1.0.1
    volumes:
      - ./production-logs:/opt/app/logs
      - ./src/main/resources/application-prod.properties:/opt/app/application-prod.properties
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOG_FILE_PATH=logs
    ports:
      - 8080:8080
    networks:
      - prd

  swagger:
    container_name: swaggerui
    image: swaggerapi/swagger-ui
    volumes:
      - ../src/main/resources/wms_openapi_def.yaml:/mnt/wms_openapi_def.yaml
    environment:
      - SWAGGER_JSON=/mnt/wms_openapi_def.yaml
    ports:
    - 8083:8080
    networks:
      - prd
networks:
  prd:
    name: prd
    driver: bridge
